name: DwarvenCoin
version: 0.0.2
api-version: 1.16
main: com.github.sowasvonbot.Main

commands:
  update:
    description: update the plugin
    usage: /<command>
    permission: DwarcenCoin.update
  force_update:
    description: Force update the plugin
    usage: /<command>
    permission: DwarvenCoin.force_update
